---
kind: pkgfile.Build
spec:
  targets:
    - u-boot
    - kernel
    - orangepi-5
  extraBuildArgs:
    - PKGS_PREFIX
    - PKGS
  makefile:
    extraVariables:
      - name: PKGS_PREFIX
        defaultValue: ghcr.io/siderolabs
      - name: PKGS
        defaultValue: v1.7.0-alpha.0-33-g3aacf03
---
kind: common.Build
spec:
  ignoredPaths:
    - go.work.sum
---
kind: auto.CustomSteps
spec:
  steps:
    - name: kernel-%
      toplevel: true
---
kind: custom.Step
name: kernel-%
spec:
  makefile:
    enabled: true
    script:
      - |
        for platform in $(shell echo $(PLATFORM) | tr "," " "); do \
          arch=`basename $$platform` ; \
          $(MAKE) docker-kernel-prepare PLATFORM=$$platform TARGET_ARGS="--tag=$(REGISTRY)/$(USERNAME)/kernel:$(TAG)-$$arch --load"; \
          docker run --rm -it --entrypoint=/toolchain/bin/bash -e PATH=/toolchain/bin:/bin -w /src -v $$PWD/kernel/build/config-$$arch:/host/.hostconfig $(REGISTRY)/$(USERNAME)/kernel:$(TAG)-$$arch -c 'cp /host/.hostconfig .config && make $* && cp .config /host/.hostconfig'; \
        done
